require 'custom.plugins.oil'
require 'custom.plugins.lsp'
require 'custom.plugins.telescope'
require 'custom.plugins.treesitter'
require 'custom.plugins.autoformat'
require 'custom.plugins.colorscheme'
require 'custom.plugins.completion'
require 'custom.plugins.spider'
require 'custom.plugins.fidget'
require 'custom.plugins.icon'
require 'custom.plugins.mini'
require 'custom.plugins.browse'
require 'custom.plugins.gitutils'
require 'custom.plugins.terminal'
require 'custom.plugins.undotree'
require 'custom.plugins.typst'
-- require 'custom.plugins.harpoon'
require 'custom.plugins.flash'
